"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { 
  Sparkles, 
  Search, 
  User, 
  Phone, 
  FileText, 
  Calendar,
  CheckCircle,
  AlertCircle
} from "lucide-react";

interface Lead {
  id: string;
  name: string;
  contact_name: string | null;
  contact_phone: string | null;
  stage: "new" | "qualified" | "converted" | "lost";
  owner_id: string | null;
  notes: string | null;
  created_at: string;
  owner?: { full_name: string } | null;
}

interface Props {
  initialLeads: Lead[];
}

function formatDate(dateStr: string) {
  return new Date(dateStr).toLocaleDateString("en-AE", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

export default function LeadsDashboardClient({ initialLeads }: Props) {
  const supabase = createClient();
  const [leads, setLeads] = useState<Lead[]>(initialLeads);
  const [searchQuery, setSearchQuery] = useState("");
  const [filterStage, setFilterStage] = useState<string>("all");

  // Handle stage change
  async function handleStageChange(leadId: string, newStage: Lead["stage"]) {
    try {
      const { error } = await supabase
        .from("leads")
        .update({ stage: newStage })
        .eq("id", leadId);

      if (error) {
        alert("Failed to update lead stage: " + error.message);
      } else {
        setLeads(prev => 
          prev.map(l => l.id === leadId ? { ...l, stage: newStage } : l)
        );
      }
    } catch (err: any) {
      alert("Error: " + err.message);
    }
  }

  // Filter leads
  const filteredLeads = leads.filter(l => {
    const matchesSearch = 
      l.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (l.owner?.full_name && l.owner.full_name.toLowerCase().includes(searchQuery.toLowerCase())) ||
      (l.notes && l.notes.toLowerCase().includes(searchQuery.toLowerCase()));
      
    const matchesStage = filterStage === "all" || l.stage === filterStage;

    return matchesSearch && matchesStage;
  });

  return (
    <div className="space-y-6 bg-[#FAF8F4] -m-4 p-6 min-h-screen">
      <div>
        <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#B8622A]">
          Pipeline
        </p>
        <h1 className="text-xl font-bold text-[#1C2321] tracking-tight mt-0.5">
          New Business Leads
        </h1>
        <p className="text-xs text-[#9A988C] mt-1">
          Monitor incoming prospects and customer visit opportunities generated by your sales team.
        </p>
      </div>

      {/* Filter and Search actions */}
      <div className="flex flex-col sm:flex-row gap-3 justify-between items-stretch sm:items-center bg-white p-4 rounded-md ring-1 ring-[#E7E2D9] shadow-sm">
        <div className="relative flex-1">
          <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-[#B4B2A9]" />
          <input
            type="text"
            placeholder="Search leads by name, rep, or outcome notes..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full h-10 rounded-sm border border-[#E7E2D9] bg-[#FDFCFA] pl-9 pr-3 text-xs text-[#1C2321] placeholder-[#B4B2A9] focus:outline-none focus:ring-1 focus:ring-[#B8622A] focus:border-[#B8622A]"
          />
        </div>
        <div className="flex items-center gap-2">
          <label className="text-xs font-bold text-[#9A988C] uppercase tracking-wider shrink-0">Stage</label>
          <select
            value={filterStage}
            onChange={(e) => setFilterStage(e.target.value)}
            className="h-10 rounded-sm border border-[#E7E2D9] bg-[#FDFCFA] px-3 text-xs text-[#1C2321] focus:outline-none focus:ring-1 focus:ring-[#B8622A]"
          >
            <option value="all">All Stages</option>
            <option value="new">New Opportunity</option>
            <option value="qualified">Qualified</option>
            <option value="converted">Converted</option>
            <option value="lost">Lost</option>
          </select>
        </div>
      </div>

      {/* Leads Feed */}
      <div className="space-y-4">
        {filteredLeads.length === 0 ? (
          <div className="rounded-md bg-white p-12 text-center ring-1 ring-[#E7E2D9]">
            <Sparkles size={32} className="mx-auto text-[#B4B2A9] mb-3 animate-pulse" />
            <p className="text-sm font-bold text-[#1C2321]">No leads found</p>
            <p className="text-xs text-[#9A988C] mt-1">No new pipeline opportunities match your criteria.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 gap-4">
            {filteredLeads.map((l) => (
              <div key={l.id} className="rounded-md bg-white p-5 ring-1 ring-[#E7E2D9] space-y-4 shadow-sm hover:shadow-md transition-all">
                <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                  <div className="space-y-1">
                    <h3 className="text-base font-bold text-[#1C2321]">{l.name}</h3>
                    <div className="flex flex-wrap items-center gap-x-4 gap-y-1.5 text-xs text-[#9A988C]">
                      <span className="flex items-center gap-1">
                        <User size={12} className="text-[#B8622A]" /> Owner: {l.owner?.full_name ?? "Unassigned"}
                      </span>
                      <span className="flex items-center gap-1 font-mono">
                        <Calendar size={12} /> {formatDate(l.created_at)}
                      </span>
                      {l.contact_name && (
                        <span className="flex items-center gap-1">
                          Contact: {l.contact_name} {l.contact_phone ? `(${l.contact_phone})` : ""}
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Inline Stage Dropdown */}
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-bold text-[#9A988C] uppercase tracking-wider">Status:</span>
                    <select
                      value={l.stage}
                      onChange={(e) => handleStageChange(l.id, e.target.value as Lead["stage"])}
                      className={`h-8 rounded-sm border px-2.5 text-xs font-bold transition-all focus:outline-none focus:ring-1 focus:ring-[#B8622A] ${
                        l.stage === "converted"
                          ? "bg-[#E8EFE4] text-[#3F6B4F] border-[#C3D6BA]"
                          : l.stage === "lost"
                          ? "bg-[#F7E7E3] text-[#A23B2E] border-[#E4B8AC]"
                          : l.stage === "qualified"
                          ? "bg-[#E7F3F7] text-[#2E7CA2] border-[#AED6E4]"
                          : "bg-[#FBEEDD] text-[#8A5620] border-[#EDCFA3]"
                      }`}
                    >
                      <option value="new">New</option>
                      <option value="qualified">Qualified</option>
                      <option value="converted">Converted</option>
                      <option value="lost">Lost</option>
                    </select>
                  </div>
                </div>

                {l.notes && (
                  <div className="bg-[#FAF8F4] p-3 rounded-sm border border-[#E7E2D9] space-y-1.5">
                    <p className="text-[10px] font-bold text-[#9A988C] uppercase tracking-wider flex items-center gap-1">
                      <FileText size={11} /> Visit Dictation Notes
                    </p>
                    <p className="text-xs text-[#6B6A63] whitespace-pre-wrap leading-relaxed">
                      {l.notes}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
